apiVersion: 1

datasources:
  - name: YouTube Analytics PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: youtube_analytics
    user: airflow
    password: airflow
    isDefault: true
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false